language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      sudo: required
      dist: xenial

install:
  - pip install pipenv
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip install pip==9.0.3
      pipenv install --dev --skip-lock
    else
      pipenv install --dev
    fi

script:
  - pipenv run tox
